### ISSUE TITLE
Always crashes in RStudio on Windows 7

### ISSUE THREAD

**Issue by thomiko** [lvaudor/graphiT#1]
I was able to install the graphiT package via devtools::install_github without problems. From within RStudio I can load the library and start the package via graphiT(). In the browser I can select data without any problems ...

![graphit-1](https://user-images.githubusercontent.com/16490122/31049629-372352c8-a637-11e7-8a42-5e5906465a42.png)

but as soon as I click on "Plot" the gray shade does not disappear ...

![graphit-2](https://user-images.githubusercontent.com/16490122/31049636-61e571e4-a637-11e7-828c-6ac6a98bb0cc.png)

... and I get the following error message in RStudio:

![graphit-3](https://user-images.githubusercontent.com/16490122/31049682-43ebda9c-a638-11e7-93e4-0c7903b3e932.png)

This is my R version, all packages are up to date:

![graphit-4](https://user-images.githubusercontent.com/16490122/31049683-4a81f242-a638-11e7-91d6-39fdde377394.png)

Any ideas why this happens, any suggestions for troubleshooting?

Merci beaucoup d'avance!

**Comment by lvaudor** [comment]
Bonjour Thomas!

Thanks for using (or at least trying to use ;-) ) graphiT. 

We get little information about what's going wrong, so, truly, this is more a guess than anything else: I'd say you might (??) have  a problem with packages' versions, maybe similar to the problem mentioned  [here](https://github.com/rstudio/shiny/issues/1726)  or a problem with [ggplot2 causing RStudio to crash](https://support.rstudio.com/hc/en-us/community/posts/207645558-RStudio-0-99-crashes-when-ggplot-is-called).

Maybe you could first try to run the app from the RGui rather than from RStudio to check whether this second hypothesis holds?

Kind regards,

Lise

**Comment by thomiko** [comment]
Bonjour Lise,

many thanks for your suggestions! I first tried the RGui approach, but this crashed as well. RGui just disappeared.

Luckily the info from your first link brought the solution. This article helped a lot: 
http://shiny.rstudio.com/articles/upgrade-R.html

I only executed the following code:
`update.packages(ask = FALSE, checkBuilt = TRUE)`
Afterwards, it worked like a breeze both in RStudio and in RGui :-)

btw: I was the guy who posted on Google Groups the solution to the "ggplot2 causing RStudio to crash" problem ;-)


Have a nice day,

Thomas

**Comment by thomiko** [comment]
btw: Thanks for your presentation at useR! 2017! Otherwise I wouldn't have come across graphiT .

**Comment by lvaudor** [comment]
Oh great! 

Thanks a lot for the feedback, solution, and extra link about upgrading packages!...
 
I should probably advertise graphiT a bit more than I've done so far, but I still feel nervous about possible crashes that'd be beyond my understanding (... so, thanks for helping me deal with my deepest fears ;-) ).

Best,

Lise
